name = "koro-compute-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]

[build]
command = "cargo install -q worker-build && worker-build --release"

[vars]
ENVIRONMENT = "production"
